# Generated by Django 5.0.4 on 2024-05-22 18:33

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=sorl.thumbnail.fields.ImageField(default='banners/default/default.jpg', upload_to='banners'),
        ),
    ]
