# Generated by Django 5.0.4 on 2024-05-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_image_profile_profile_picture_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=140),
        ),
    ]
